<?php
$product = $block->getProduct();

$document_text = $product->getData('bynder_document');
//echo "<pre>"; print_r($document_text); exit;

if (!empty($document_text)) {

    $document_array = json_decode($document_text, true);
	$document_array = $document_array['asset_list'];
    $html = "";
    if (!empty($document_array)) {
        foreach ($document_array as $doc) {
			//echo "<pre>"; print_r($doc); 
            $lable = explode("/", $doc['item_url']);
			//echo "<pre>"; print_r($lable); 
            $html .= '<li><a href="' . $doc['item_url'] . '" target="_blank">' . $lable[2] . '</a></li>';
        }
    }
    ?>

<ul>
    <?= /* @noEscape */ $html ?>
</ul>
<?php } ?>
