<?= $block->getButtonHtml(); ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function($) {
        var ajax_request;
        var test = 1;
        $('#bt_id_1').click(function() {
            var product_sku = $('textarea#byndersyncdata_bynder_sync_data_sku').val();
            var select_attribute = $('select#byndersyncdata_bynder_sync_data_select').val();
            var select_store = $('select#byndersyncdata_bynder_sync_data_store_dropdown').val();
            var params = {
                product_sku: product_sku,
                select_attribute: select_attribute,
                select_store: select_store
            };

            var sku_to_array = product_sku.split(",");
            var total_skus = sku_to_array.length;
            console.log("Total sku=>"+total_skus);
            var batch = 20;
            var start = 0;
            var batch_value = batch;
            var slicedArray = sku_to_array.slice(0, batch);

            var total_module_Val = total_skus % batch;
            var perfect_working = total_skus - total_module_Val;
            var total_loops = perfect_working / batch;

            var i=0;
            var k = 0;
            var next_value = batch;

            for(i=0;i<total_loops;i++){
                var slicedArray = sku_to_array.slice(k, next_value);
                k = k+batch;
                next_value = next_value + batch;
                if(test == 0){
                    break;
                }
                var new_skus_list = slicedArray.join(",");
                var params = {
                    product_sku: new_skus_list,
                    select_attribute: select_attribute,
                    select_store: select_store
                };
                var check_all_extra = new_skus_list.split(",");
                console.log(check_all_extra);
                //do_ajax_call(params);
            }

            var new_skus_list = sku_to_array.slice(perfect_working, total_skus);
            var params = {
                product_sku: new_skus_list,
                select_attribute: select_attribute,
                select_store: select_store
            };
            do_ajax_call(params);
        });

        function do_ajax_call(params){
            new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()); ?>', {
                parameters: params,
                loaderArea: true,
                beforeSend: function() {
                    $('body').trigger('processStart');
                },
                onSuccess: function(transport) {                    
                    var resultText = '';
                    if (transport.responseJSON.status == 1) {
                        resultText = transport.statusText;
                        //console.log(transport);
                        $('#byndersyncdata_bynder_sync_data_sku').text('');
                        $(".success-msg-sync").show();
                        $(".error-msg-sync").hide();
                        $(".success-msg-sync").html(transport.responseJSON.message);
                        setTimeout(function() { 
                            $('.success-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    } else {
                        //console.log(transport.responseJSON.message);
                        resultText = transport.responseJSON.message
                        $('#byndersyncdata_bynder_sync_data_sku').text('');
                        $(".error-msg-sync").show();
                        $(".success-msg-sync").hide();
                        $(".error-msg-sync").html(resultText);
                        setTimeout(function() {
                            $('.error-msg-sync').delay(5000).fadeOut('slow');
                        }, 5000);
                    }
                }
            });
        }
    });
</script>


<style>
    .success-msg-sync,
    .error-msg-sync {
        margin: 10px 0;
        padding: 10px;
        border-radius: 3px 3px 3px 3px;
    }

    .success-msg-sync {
        color: #270;
        background-color: #DFF2BF;
    }

    .error-msg-sync {
        color: #D8000C;
        background-color: #FFBABA;
    }
</style>
<div class="success-msg-sync" style="display:none;"></div>
<div class="error-msg-sync" style="display:none;"></div>
